# Site settings
title: Yang Lin, Ph.D.
email: yanglin at berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  I am a postdoctoral scholar at UC Berkeley.
  I study biogeochemistry and ecosystem ecology. 
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://ylinterra.com" # the base hostname & protocol for your site
gscholar: TZ2NznwAAAAJ
publons: 339957
twitter_username: lesterlin
github_username:  deltac13
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
encoding: utf-8

# Google services
google_analytics: UA-18272332-4
